name: My First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.3.0

            - name: Welcome message
              run: echo "my first Github Actions Job"

            - name: list files
              run: ls

            - name: Read file
              run: cat README.md